#!/usr/bin/python

import smbus
import math
from time import sleep

# Power management registers
power_mgmt_1 = 0x6b
power_mgmt_2 = 0x6c

def read_byte(address,adr):
    return bus.read_byte_data(address, adr)

def read_word(address,adr):
    high = bus.read_byte_data(address, adr)
    low = bus.read_byte_data(address, adr+1)
    val = (high << 8) + low
    return val

def read_word_2c(address,adr):
    val = read_word(address,adr)
    if (val >= 0x8000):
        return -((65535 - val) + 1)
    else:
        return val

def dist(a,b):
    return math.sqrt((a*a)+(b*b))

def get_y_rotation(x,y,z):
    radians = math.atan2(x, dist(y,z))
    return -math.degrees(radians)

def get_x_rotation(x,y,z):
    radians = math.atan2(y, dist(x,z))
    return math.degrees(radians)

bus = smbus.SMBus(2) # or bus = smbus.SMBus(1) for Revision 2 boards
address = 0x69       # This is the address value read via the i2cdetect command

# Now wake the 6050 up as it starts in sleep mode
bus.write_byte_data(address, power_mgmt_1, 0)

cont = 1

while cont == 1:

	gyro_xout = read_word_2c(address,0x43)
	gyro_yout = read_word_2c(address,0x45)
	gyro_zout = read_word_2c(address,0x47)

	# print "gyro_xout: ", gyro_xout, " scaled: ", (gyro_xout / 131)
	# print "gyro_yout: ", gyro_yout, " scaled: ", (gyro_yout / 131)
	# print "gyro_zout: ", gyro_zout, " scaled: ", (gyro_zout / 131)

	accel_xout = read_word_2c(address,0x3b)
	accel_yout = read_word_2c(address,0x3d)
	accel_zout = read_word_2c(address,0x3f)

	accel_xout_scaled = accel_xout / 16384.0
	accel_yout_scaled = accel_yout / 16384.0
	accel_zout_scaled = accel_zout / 16384.0

	#print "accel_xout: ", accel_xout, " scaled: ", accel_xout_scaled
	#print "accel_yout: ", accel_yout, " scaled: ", accel_yout_scaled
	#print "accel_zout: ", accel_zout, " scaled: ", accel_zout_scaled
	print round(accel_xout_scaled,5) , ",", round(accel_yout_scaled,5), ",", round(accel_zout_scaled,5)

	#print "x rotation: " , get_x_rotation(accel_xout_scaled, accel_yout_scaled, accel_zout_scaled)
	#print "y rotation: " , get_y_rotation(accel_xout_scaled, accel_yout_scaled, accel_zout_scaled)
	sleep(0.02)
